### ISSUE TITLE
[RFC] Reorganize directory structure

### ISSUE THREAD

**Issue by chivay** [CERT-Polska/ursadb#19]
Currently, there's a lot of files in the root directory of the project which seems a bit messy.
My idea would be to split code into 3 directories:
*  `libursa` - after library target in CMake
*  `src` - containing source files of executables (with one directory per executable (?))
* `third-party` - with 3rd party libraries

(EDIT) Or maybe move `libursa` into `src`? Either way, i'm looking for suggestions :thinking: 

@msm-code @icedevml

**Comment by msm-code** [comment]
what do you mean by the first part (after library target)? The location when the compiled files will appear?

I'd also like to:

- get rid of ./contrib - this is straightforward, we don't even package ursadb as .deb right now (that was the original goal)
- get rid of ./test - having static files for testing in the repository is not wrong by itself, but this means that ./ursadb_test will only run correctly from the repository root (and it writes to files in cwd to make things worse).

But overall, a nice idea :+1:

**Comment by chivay** [comment]
>what do you mean by the first part

Directory named after ursa library target.
I think it's reasonable to separate core library source files and basically everything else.

**Comment by msm-code** [comment]
:+1: yes

**Comment by chivay** [comment]
Reorganization preview: 41ab2ad53

**Comment by chivay** [comment]
resolved in #22
