### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by DigiAngel** [CERT-Polska/ursadb#2]
FYI...per the instructions here's my results:
~~~
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_C_COMPILER:

    gcc-7

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_CXX_COMPILER:

    g++-7

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
~~~
cmake version is 3.7.2.  Thank you.

**Comment by icedevml** [comment]
Hello, you need to install `g++-7` package. If you have relatively new Linux distro then it should be available from the package manager. In either case you may use ppa or use Docker which was provided with the project.

**Comment by DigiAngel** [comment]
Ah...yes I'm on gcc/g++ 6.  Can you point me to where the ppa is?  Thank you :)

**Comment by icedevml** [comment]
What distribution are you using? Please provide name and version.

**Comment by DigiAngel** [comment]
Ah...yea that would have helped...sorry..need more coffee ;)  Debian stretch.

**Comment by icedevml** [comment]
In such case I suggest searching for a ppa which would provide g++-7 for Debian Stretch or building UrsaDB using Dockerfile provided:

```
docker build -t ursadb .
docker run ursadb
```

**Comment by DigiAngel** [comment]
Thank you.
