### ISSUE TITLE
Command failed: corrupted index

### ISSUE THREAD

**Issue by ctyk3322** [CERT-Polska/ursadb#3]
Hello,

I was using your mquery project and when I tried to index samples with ursadb I get the following error after indexing a few samples. 

ursadb_1  | new dataset
ursadb_1  | Command failed: corrupted index, file is too small
ursadb_1  | worker finished: 3, he was doing task 3

**Comment by icedevml** [comment]
What commands were you running previously?

**Comment by icedevml** [comment]
Closing due to lack of response.
