### ISSUE TITLE
Add a new command: `index with taints`

### ISSUE THREAD

**Issue by msm-code** [CERT-Polska/ursadb#31]
Right now, if I want to have a new dataset tagged as `xyz`, I need to run two separate commands:

```
index "/xxx" with [gram3]
dataset [id of the newly created dataset] taint "xyz";
``` 

This is pretty complex, especially since indexing can take a long time and dataset ID is not known upfront. Instead, I'd like to have a combined command (syntax subject to change):

```
index "/xxx" with [gram3] with taints ["xyz"]
```

**Comment by ITAYC0HEN** [comment]
Why "taint" was chosen for the emaning of "label" or "tag"?
Anyways, good idea.

What about 
```
index "/xxx" with [gram3] as ["xyz"]
```

**Comment by msm-code** [comment]
Not sure :thinking:. That's how they were called during the design. I think that I sometimes refer to them as `tag` in mquery, which may cause even more confusion.

Probably because the original goal was to mark some datasets as `special`, so they won't get merged into other, `clean` ones.

I don't think this feature is used outside by anyone outside of cert.pl and mquery internally, so it's not too late change it, if you think it's worth it.

**Comment by ITAYC0HEN** [comment]
Absolutely up to you :)  I don't think it is a describing name, but maybe it's a popular term I've never heard in relation to tagging and labeling. 

![Screenshot_20200412-082429](https://user-images.githubusercontent.com/20182642/79061275-1ad08300-7c97-11ea-8a96-7f461a432af8.jpg)

**Comment by msm-code** [comment]
Probably stolen from https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

> Taints are the opposite – they allow a node to repel a set of pods.
> (...) One or more taints are applied to a node; this marks that the node should not accept any pods that do not tolerate the taints.

But yeah, `tag` may make more sense in this context :thinking:

**Comment by msm-code** [comment]
Closing since this feature is already implemented (with the original name and original syntax)
