### ISSUE TITLE
Command Failed: index

### ISSUE THREAD

**Issue by rohaaan** [CERT-Polska/ursadb#4]
Hi,

when we start indexing a location following error occurs:
ERR filesystem error: cannot get file size: No such file or directory [/home/ubuntu/DB/home/ubuntu/DB/gram3.set.63df787f.db.ursa]

I dont understand why DB root folder path is getting prepended?

In this case DB root path is /home/ubuntu/DB

Please help...

**Comment by icedevml** [comment]
What is current working directory of UrsaDB in this case?

**Comment by rohaaan** [comment]
/home/ubuntu/ursadb/build

**Comment by icedevml** [comment]
I have trouble reproducing that problem. Could you tell which location are you indexing and what commands exactly are you issuing?

**Comment by rohaaan** [comment]
location being indexed: /home/ubuntu/samples
Current Working Directory of Ursadb: /home/ubuntu/ursadb/build
commands issued:
ubuntu@ubuntu:~$ cd ursadb-cli/
ubuntu@ubuntu:~/ursadb-cli$ python ursaclient.py 
[ ] Connecting: tcp://localhost:9281
[+] Connected
> index "/home/ubuntu/samples"
task 2    0.21% [....................]
task 2    0.58% [....................]
task 2    0.71% [....................]
task 2    1.08% [....................]
task 2    10.64% [##..................]
task 2    10.64% [##..................]
task 2    10.64% [##..................]
task 2    11.09% [##..................]
task 2    11.63% [##..................]
task 2    12.09% [##..................]
task 2    12.59% [##..................]
task 2    13.05% [##..................]
task 2    13.54% [##..................]
task 2    21.27% [####................]
task 2    21.27% [####................]
task 2    21.27% [####................]
ERR filesystem error: cannot get file size: No such file or directory [/home/ubuntu/DB/home/ubuntu/DB/gram3.set.63df787f.db.ursa]

**Comment by icedevml** [comment]
Could you pull from `fix-4` branch, remove contents of `/home/ubuntu/DB` and try again? I think I found the problem.

**Comment by icedevml** [comment]
Hello @raw-data, thanks for your confirmation. After a little more testing `fix-4` will be merged with master.

**Comment by rohaaan** [comment]
@icedevml :- I will wait for the fix-4 to be merged.

**Comment by icedevml** [comment]
Fix was merged to master.

**Comment by rohaaan** [comment]
Hi,
I downloaded the changed master build it... still same results...
![screenshot from 2018-07-09 19-29-58](https://user-images.githubusercontent.com/2869208/42454936-84252c68-83ae-11e8-891f-90a80dc5f36c.png)

**Comment by rohaaan** [comment]
Also tried by downloading fix-4 branch ... still index command fails with 
ERR filesystem error: cannot get file size: No such file or directory [/home/ubuntu/DB/home/ubuntu/DB/gram3.set.b6e7a926.db.ursa]

**Comment by icedevml** [comment]
@rohaan: Have you removed all database files before testing fix from fix-4 (right now it's merged to master)? Could you give the contents of `db.ursa`, `files.*.db.ursa` and `set.*.db.ursa`?

**Comment by rohaaan** [comment]
yes.. i had cleared the entire folder....
