### ISSUE TITLE
allocate memory not released after indexing

### ISSUE THREAD

**Issue by raw-data** [CERT-Polska/ursadb#5]
After indexing a new path, allocated memory for **ursadb** process is never released. 
See below for an example:

Tested branch: `fix-4`
Indexing a new path with (from ursadb-client): index "/mnt/samples/" with [gram3];

-- Before indexing --
ursadb 3.1MiB

-- After index --
ursadb 2.5GiB
it stays in this state unless restarted

-- After restarting ursadb process --
ursadb 4.3MiB

**Comment by icedevml** [comment]
Thanks for your report, looks like there may be some problem with mmap or other source of memory leak. I will inspect it soon.

**Comment by icedevml** [comment]
I've reproduced this issue. It's related to `FlatIndexBuilder` while `BitmapIndexBuilder` seems to work without memory issues. Flat builder is being chosen when files to be indexed are small (up to few megabytes).

**Comment by icedevml** [comment]
I'm currently testing a fix on branch `fix-5`, seems like the problem was identified. Could you check, @raw-data?

**Comment by raw-data** [comment]
@icedevml looks good, see below

testing system: 16GB RAM
/storage/samples/ (65536 samples ~ 60G)
ursadb-cli: index "/storage/samples/" with [gram3];

ursadb memory usage:

-- Before indexing --
3.8 MiB

-- During indexing ---
 - between 500 - 800 MiB
 - just one spike up to 2.7GiB while processing @ 23%, back to normal @ 25%

-- After indexing --
740 MiB, it stays in this state unless restarted

-- After restarting ursadb --
12.5 MiB

No other memory leaks observed

**Comment by icedevml** [comment]
About this `740 MiB` after indexing - I'm not really sure how this allocation is counted, since ursadb is using a lot of mmap, so things may get cached when there is a free memory. Anyway I will take few more hours to profile allocations, maybe there are some smaller leaks which I've missed.
