### ISSUE TITLE
[Question] Best practices

### ISSUE THREAD

**Issue by RamonBeast** [CERT-Polska/ursadb#6]
I download periodically malicious files from different sources and put them on a common storage. What are the best practices that you suggest to index new files, while avoiding to unnecessarily re-index those that have already been scanned?

Thank you

**Comment by icedevml** [comment]
Hello,

some hint is provided here: https://github.com/CERT-Polska/ursadb-cli#indexing-cuckoos-dumps

I think something like this is the simplest solution:

```
find /some/binaries -maxdepth 2 -type f > /tmp/ursadb-list.txt
python3 ursaclient.py --cmd 'index from list "/tmp/ursadb-list.txt";' tcp://ursadb:9281
```

This essentially stands for "create a list of files modified within last 2 days and tell the database to index them". UrsaDB will automatically de-duplicate, so stuff will be not indexed twice.

Where `tcp://ursadb:9281` should be a `host:port` to your UrsaDB and `/tmp/ursadb-list.txt` should be some path accessible by UrsaDB process (shared volume? same machine/container).

**Comment by msm-code** [comment]
`What are the best practices that you suggest to index new files, while avoiding to unnecessarily re-index those that have already been scanned?`

If you don't have a lot of files, you can just reindex the whole directory. The same file will never be indexed multiple times (deduping is based on file path).

**Comment by RamonBeast** [comment]
Thanks @icedevml for this information, in particular it's interesting that UrsaDB does de-duplication, I was not aware of that. @msm-code I do have several TBs of binaries so re-index everything is an option that I would like to avoid if possible.

Now that I know about de-duplication I feel more confident to make experiments. My initial thought was to create a micro-service that monitors the storage (using kernel fs notifications, via inotify) to populate a queue of elements that is dispatched to ursaclient.py and I think, given your hints, that this might work for my use case.

Again, thank you very much for providing me with valuable information!

**Comment by RamonBeast** [comment]
Thanks again @icedevml I'll begin to jot down some code for the service while I wait for the admin manual. I will then proceed by indexing only every few thousands files (instead of every file as I was planning) and running ``compact`` on a daily basis to avoid fragmentation. You help has been really precious and thanks to you and your team for your work!
