### ISSUE TITLE
Reindexing caused a zmq protocol violation

### ISSUE THREAD

**Issue by msm-code** [CERT-Polska/ursadb#66]
After recent changes (I assume) we've added or removed a zmq frame somewhere, and reindexing operation ended up with 

```
ursadb_1      | Runtime error: Expected zero-size frame
```

Probably during taking down lock in the coordinator, I didn't check

In result:

1) the whole operation failed (I assume)
2) the worker is now deadlocked, and it'll wait for the confirmation forever

We should:

1) fix the root cause of the bug
2) handle zmq errors more gracefully

**Edit** I think the core cause of the bug might've been reindexing a [gram3] dataset with [gram3, text4] indexes only. Probably didn't expect to drop files?

**Comment by icedevml** [comment]
Unable to reproduce, tried:

> reindexing a [gram3] dataset with [gram3, text4] indexes only

**Comment by msm-code** [comment]
That should be `reindexing a [gram3] dataset with [text4] indexes only`, but hmm, yeah, I can't reproduce it too

**Comment by msm-code** [comment]
![ss](https://user-images.githubusercontent.com/7026881/79381326-1b506e80-7f62-11ea-95ed-78820467088e.png)
This won't make debugging easier...

**Comment by msm-code** [comment]
Since noone managed to reproduce this issue it makes no sense to block the release with it...

I've created a pull request to make this more debuggable in the future.
